/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import DataEncoder.TextFieldCharLimit;
import Login.Login;
import ServiceInterface.service;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AbeXo
 */
public class Admin extends javax.swing.JFrame {
    Registry reg;
    service service;
    private String ipaddress;
    private String username;
    private static ArrayList arrcopy;
    private static int editable=0;
    private static int selectedIndex;
    
    /**
     * Creates new form administration page
     */
    public Admin() {
        initComponents();
        selectedIndex=0;
         try{
       reg=LocateRegistry.getRegistry("127.0.0.1", 1099);
       service=(service)reg.lookup("digitalcasemanagment");
       }catch(Exception ex){
       System.out.println(ex.getMessage());}    
            
         fname.setDocument(new TextFieldCharLimit(20));//set a chracter limit of 20 for the first name text field
        lname.setDocument(new TextFieldCharLimit(20));//set a chracter limit of 20 for the last name text field
        address.setDocument(new TextFieldCharLimit(40));//set a chracter limit of 40 for the address text field
        phonenumber.setDocument(new TextFieldCharLimit(10));//set a chracter limit of 10 for the phone text field
        editfname.setDocument(new TextFieldCharLimit(20));//set a chracter limit of 20 for the first name for the edit first name text field
        editlname.setDocument(new TextFieldCharLimit(20));//set a chracter limit of 20 for the last name for the edit last name text field 
        editaddress.setDocument(new TextFieldCharLimit(40));//set a chracter limit of 20 for the address for the edit address text field
        editphone.setDocument(new TextFieldCharLimit(10));//set a chracter limit of 10 for the phone for edit phone number text field
         updateuser.setVisible(false);//make the update the user information button hidden at first
         
         
         registeruserticker.setVisible(true);
         editprofilerticker.setVisible(false);
         logreportticker.setVisible(false);
         
         
         
    }
    public void setuname(String uname)
        {
            this.username=uname;
        }
        public void setip(String ipaddr)
        {
            this.ipaddress=ipaddr;
        }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        attachfile = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        useridsearch = new javax.swing.JTextField();
        searchuser = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        editlname = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        editfname = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        editpersonid = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        editaddress = new javax.swing.JTextField();
        editacctype = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        edituserclear = new javax.swing.JButton();
        editphone = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        changestatususer = new javax.swing.JButton();
        updateuser = new javax.swing.JButton();
        editgender = new javax.swing.JComboBox<>();
        jLabel73 = new javax.swing.JLabel();
        registerUser = new javax.swing.JPanel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        personId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        accountType = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        specialization = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        Register = new javax.swing.JButton();
        clear1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        birthdate = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        phonenumber = new javax.swing.JTextField();
        caseReport = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel56 = new javax.swing.JLabel();
        reportsearch = new javax.swing.JButton();
        pagedetail = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        registeruserticker = new javax.swing.JLabel();
        logout1 = new javax.swing.JButton();
        logreportticker = new javax.swing.JLabel();
        editprofilerticker = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(25, 51, 59));

        jTabbedPane1.setBackground(new java.awt.Color(25, 51, 59));
        jTabbedPane1.setName("MENU"); // NOI18N
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(300, 200));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel65.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel65.setText("User Name");

        useridsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridsearchActionPerformed(evt);
            }
        });

        searchuser.setBackground(new java.awt.Color(0, 0, 0));
        searchuser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchuser.setForeground(new java.awt.Color(255, 255, 255));
        searchuser.setText("Search");
        searchuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchuserActionPerformed(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(33, 139, 209));
        jSeparator7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        editlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editlnameActionPerformed(evt);
            }
        });
        editlname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editlnameKeyPressed(evt);
            }
        });

        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel66.setText(" First Name");

        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel67.setText("Last Name");

        editfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editfnameActionPerformed(evt);
            }
        });
        editfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editfnameKeyPressed(evt);
            }
        });

        jLabel68.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel68.setText("Person Id");

        editpersonid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editpersonidActionPerformed(evt);
            }
        });
        editpersonid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editpersonidKeyPressed(evt);
            }
        });

        jLabel69.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel69.setText("Account Type");

        editaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaddressActionPerformed(evt);
            }
        });

        editacctype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editacctypeActionPerformed(evt);
            }
        });
        editacctype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editacctypeKeyPressed(evt);
            }
        });

        jLabel70.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel70.setText("Address");

        edituserclear.setBackground(new java.awt.Color(51, 51, 51));
        edituserclear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        edituserclear.setForeground(new java.awt.Color(255, 255, 255));
        edituserclear.setText("Clear");
        edituserclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edituserclearActionPerformed(evt);
            }
        });

        editphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editphoneActionPerformed(evt);
            }
        });
        editphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editphoneKeyPressed(evt);
            }
        });

        jLabel71.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel71.setText("Phone number");

        changestatususer.setBackground(new java.awt.Color(0, 0, 0));
        changestatususer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        changestatususer.setForeground(new java.awt.Color(255, 255, 255));
        changestatususer.setText("Change Status");
        changestatususer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changestatususerActionPerformed(evt);
            }
        });

        updateuser.setBackground(new java.awt.Color(0, 0, 0));
        updateuser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        updateuser.setForeground(new java.awt.Color(255, 255, 255));
        updateuser.setText("UPdate");
        updateuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateuserActionPerformed(evt);
            }
        });

        editgender.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        editgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        editgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editgenderActionPerformed(evt);
            }
        });

        jLabel73.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel73.setText("Gender");

        javax.swing.GroupLayout attachfileLayout = new javax.swing.GroupLayout(attachfile);
        attachfile.setLayout(attachfileLayout);
        attachfileLayout.setHorizontalGroup(
            attachfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attachfileLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(attachfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attachfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel71, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(attachfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attachfileLayout.createSequentialGroup()
                        .addComponent(editgender, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(attachfileLayout.createSequentialGroup()
                        .addGroup(attachfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(attachfileLayout.createSequentialGroup()
                                .addComponent(editfname, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(attachfileLayout.createSequentialGroup()
                                .addComponent(editacctype, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(attachfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(attachfileLayout.createSequentialGroup()
                                .addComponent(editlname, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(changestatususer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(252, 252, 252))
                    .addGroup(attachfileLayout.createSequentialGroup()
                        .addComponent(editphone, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editpersonid, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(attachfileLayout.createSequentialGroup()
                .addGroup(attachfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attachfileLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(useridsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchuser, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(attachfileLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(attachfileLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(updateuser, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(edituserclear, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        attachfileLayout.setVerticalGroup(
            attachfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attachfileLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(attachfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(useridsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchuser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(attachfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attachfileLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(attachfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editlname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editfname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(attachfileLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(changestatususer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(attachfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attachfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editacctype, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(attachfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(attachfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editphone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editpersonid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(attachfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editgender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel73))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(attachfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateuser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edituserclear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );

        jTabbedPane1.addTab("Edit Profile", attachfile);

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnameKeyPressed(evt);
            }
        });

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lnameKeyPressed(evt);
            }
        });

        gender.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("First Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Last Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Address");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Gender");

        jLabel8.setBackground(new java.awt.Color(0, 200, 255));
        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 200, 255));
        jLabel8.setText("Account Information");

        jSeparator1.setBackground(new java.awt.Color(33, 139, 209));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setBackground(new java.awt.Color(0, 200, 255));
        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 200, 255));
        jLabel9.setText("Basic Inforamtion");

        personId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personIdActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Person ID");

        accountType.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        accountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excutive.J", "Data Encoder", "User" }));
        accountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountTypeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Account Type");

        specialization.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        specialization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civil Affairs", "Criminal Trial", "Labor Dispute" }));
        specialization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specializationActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Specialization");

        jSeparator2.setBackground(new java.awt.Color(33, 139, 209));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setBackground(new java.awt.Color(0, 200, 255));
        jLabel13.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 200, 255));
        jLabel13.setText("External Inforamtion");

        Register.setBackground(new java.awt.Color(0, 0, 0));
        Register.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Register.setForeground(new java.awt.Color(255, 255, 255));
        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        clear1.setBackground(new java.awt.Color(0, 0, 0));
        clear1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clear1.setForeground(new java.awt.Color(255, 255, 255));
        clear1.setText("Clear");
        clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear1ActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(33, 139, 209));
        jSeparator3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel16.setText("Birth Date");

        jLabel39.setText("Phone Number");

        phonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumberActionPerformed(evt);
            }
        });
        phonenumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phonenumberKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout registerUserLayout = new javax.swing.GroupLayout(registerUser);
        registerUser.setLayout(registerUserLayout);
        registerUserLayout.setHorizontalGroup(
            registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerUserLayout.createSequentialGroup()
                .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerUserLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1)))
                    .addGroup(registerUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(registerUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerUserLayout.createSequentialGroup()
                        .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(149, Short.MAX_VALUE))
                    .addGroup(registerUserLayout.createSequentialGroup()
                        .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personId, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountType, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(registerUserLayout.createSequentialGroup()
                                .addComponent(specialization, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(275, 275, 275))))
                    .addGroup(registerUserLayout.createSequentialGroup()
                        .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(137, 137, 137)
                        .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(registerUserLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(registerUserLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(522, Short.MAX_VALUE)))
            .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(registerUserLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(142, Short.MAX_VALUE)))
        );
        registerUserLayout.setVerticalGroup(
            registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerUserLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(3, 3, 3)
                .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(specialization, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
            .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(registerUserLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(477, Short.MAX_VALUE)))
            .addGroup(registerUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(registerUserLayout.createSequentialGroup()
                    .addGap(115, 115, 115)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(392, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Register User", registerUser);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Activites"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel56.setText("System Log Information ");

        reportsearch.setBackground(new java.awt.Color(0, 0, 0));
        reportsearch.setForeground(new java.awt.Color(255, 255, 255));
        reportsearch.setText("Search");
        reportsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout caseReportLayout = new javax.swing.GroupLayout(caseReport);
        caseReport.setLayout(caseReportLayout);
        caseReportLayout.setHorizontalGroup(
            caseReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caseReportLayout.createSequentialGroup()
                .addGroup(caseReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(caseReportLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(caseReportLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(reportsearch)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        caseReportLayout.setVerticalGroup(
            caseReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caseReportLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(caseReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(reportsearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Log Report", caseReport);

        pagedetail.setBackground(new java.awt.Color(60, 83, 89));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Federal First Degree Court Of Ethiopia");

        javax.swing.GroupLayout pagedetailLayout = new javax.swing.GroupLayout(pagedetail);
        pagedetail.setLayout(pagedetailLayout);
        pagedetailLayout.setHorizontalGroup(
            pagedetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagedetailLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pagedetailLayout.setVerticalGroup(
            pagedetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagedetailLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        logo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataEncoder/logosfinal.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(49, 152, 222));
        jLabel2.setText("Digital Case Managment");

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Edit Profile");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataEncoder/003-case-study.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Log Report");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataEncoder/001-note.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Register User");

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataEncoder/003-resume.png"))); // NOI18N

        registeruserticker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataEncoder/check.png"))); // NOI18N

        logout1.setBackground(new java.awt.Color(25, 51, 59));
        logout1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        logout1.setForeground(new java.awt.Color(255, 255, 255));
        logout1.setText("Log Out");
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });

        logreportticker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataEncoder/check.png"))); // NOI18N

        editprofilerticker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataEncoder/check.png"))); // NOI18N

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registeruserticker, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editprofilerticker, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logreportticker, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1092, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(pagedetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagedetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                    .addComponent(registeruserticker, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(editprofilerticker, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logreportticker, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout1)
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void useridsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useridsearchActionPerformed

    private void searchuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchuserActionPerformed

        String userid;
        String compare="no value";
        String summaryOfPerson;
        ArrayList arr=new ArrayList();
        userid=useridsearch.getText();

        if(userid.equals("")){JOptionPane.showMessageDialog(null,"please the user id ");}
        else{
            try {
                arr=(ArrayList) service.viewPerson(userid);//calling the RMI method view person in the server

                //check if there is no data in the array list object
                if(arr.get(0).equals(compare))
                {
                    JOptionPane.showMessageDialog(null,"user doesn't exist");//display the information
                }
                else
                {
                    try {
                        service.logresgister(ipaddress,username, "check account to edit", userid);
                    } catch (RemoteException ex) {
                        Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
                    } 

                    editable=1;
                    editpersonid.setText((String) arr.get(0));//set the person id filed by the array lit first item
                    editfname.setText((String) arr.get(1));//set the first name filed by the array lit second item
                    editlname.setText((String) arr.get(2));//set the last name filed by the array lit third item
                    editaddress.setText((String) arr.get(3));//set the address filed by the array lit fourth item
                    editacctype.setText((String) arr.get(4));//set the account type  filed by the array lit fifth item
                    editphone.setText((String) arr.get(5));//set the phone number filed by the array lit sixth item
                    editpersonid.setEditable(false); //make the person id field uneditable
                    editacctype.setEditable(false);//make the account field uneditable
                    updateuser.setVisible(true);//make the update button visible after the information is avialble in the data base
                }
            }catch(NullPointerException e) {
                System.out.println("NullPointerException thrown!");
            }           catch (RemoteException ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_searchuserActionPerformed

    private void editlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editlnameActionPerformed

    private void editlnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editlnameKeyPressed
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isISOControl(c))
        {
            editlname.setEditable(true);
        }
        else
        {
            editlname.setEditable(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_editlnameKeyPressed

    private void editfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editfnameActionPerformed

    private void editfnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editfnameKeyPressed
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isISOControl(c))
        {
            editfname.setEditable(true);
        }
        else
        {
            editfname.setEditable(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_editfnameKeyPressed

    private void editpersonidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editpersonidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editpersonidActionPerformed

    private void editpersonidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editpersonidKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_editpersonidKeyPressed

    private void editaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editaddressActionPerformed

    private void editacctypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editacctypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editacctypeActionPerformed

    private void editacctypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editacctypeKeyPressed
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isISOControl(c))
        {
            editlname.setEditable(true);
        }
        else
        {
            editlname.setEditable(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_editacctypeKeyPressed

    private void edituserclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edituserclearActionPerformed
        editpersonid.setText("");
        editfname.setText("");
        editlname.setText("");
        editaddress.setText("");
        editacctype.setText("");
        editphone.setText("");
        useridsearch.setText("");
    }//GEN-LAST:event_edituserclearActionPerformed

    private void editphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editphoneActionPerformed

    private void editphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editphoneKeyPressed
        char c=evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c))
        {
            editphone.setEditable(true);
        }
        else
        {
            editphone.setEditable(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_editphoneKeyPressed

    private void changestatususerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changestatususerActionPerformed
        String uname;
        String result;
        if(editable==1)
        {
            uname=useridsearch.getText();
            try {
                result=service.changestatus(uname);
                if(result.equals("successful operation"))
                {
                    try {
                        service.logresgister(ipaddress,username, "Disable the account",uname);
                    } catch (RemoteException ex) {
                        Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    JOptionPane.showMessageDialog(null,"sucessful operation");
                    editfname.setText("");//set the first name field empty after the operation
                    editlname.setText("");//set the last name field empty after the operation
                    editaddress.setText("");//set the address field empty after the operation
                    editphone.setText("");//set the phone number field empty after the operation
                    editacctype.setText("");//set the account type field empty after the operation
                    editpersonid.setText("");//set the person id  field empty after the operation
                    useridsearch.setText("");//set the user name field empty after the operation
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"unsucessful operation");
                }
            } catch (RemoteException ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_changestatususerActionPerformed

    private void updateuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateuserActionPerformed
        String firstname,lastname,addr,phone,sex,personid;
        String result = null;
        firstname=editfname.getText();//set the first name field into the variable
        lastname=editlname.getText();//set the last name field into the variable
        addr=editaddress.getText();//set the address field into the variable
        phone=editphone.getText();//set the phone field into the variable
        sex=(String)editgender.getSelectedItem();//set the gender field into the variable
        personid=editpersonid.getText();//set the person id field into the variable
        if((firstname.equals(""))||(lastname.equals(""))|| addr.equals("")|| phone.equals(""))
        {
            JOptionPane.showMessageDialog(null,"fill out empty fields");
        }
        else{
            try {
                result=service.updateUser(firstname,lastname,addr,phone,sex,personid);
                if(result.equals("successful operation"))
                {
                    try {
                        service.logresgister(ipaddress,username, "Update person information",personid);
                    } catch (RemoteException ex) {
                        Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    JOptionPane.showMessageDialog(null,"sucessful operation");
                    editfname.setText("");//set the first name field empty after the operation
                    editlname.setText("");//set the last name field empty after the operation
                    editaddress.setText("");//set the address field empty after the operation
                    editphone.setText("");//set the phone number field empty after the operation
                    editacctype.setText("");//set the account type field empty after the operation
                    editpersonid.setText("");//set the person id  field empty after the operation
                    useridsearch.setText("");//set the user name field empty after the operation
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"unsucessful operation");
                }
            } catch (RemoteException ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_updateuserActionPerformed

    private void editgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editgenderActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void fnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isISOControl(c))
        {
            fname.setEditable(true);
        }
        else
        {
            fname.setEditable(false);
        }
    }//GEN-LAST:event_fnameKeyPressed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void lnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameKeyPressed
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isISOControl(c))
        {
            lname.setEditable(true);
        }
        else
        {
            lname.setEditable(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_lnameKeyPressed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void personIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personIdActionPerformed

    private void accountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountTypeActionPerformed

    private void specializationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specializationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specializationActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        // TODO add your handling code here:
        String firstname,lastname,addr,id,special,phone,sex,account,bsdate;
        String result="";
        int bacc;
        Date bdate;
        firstname=fname.getText();
        lastname=lname.getText();
        addr=address.getText();
        id=personId.getText();
        account=(String)accountType.getSelectedItem();
        bdate=birthdate.getDate();
        SimpleDateFormat sdf=new SimpleDateFormat("YYYY/MM/DD");
        bsdate=sdf.format(bdate);
        phone=phonenumber.getText();
        special=(String)specialization.getSelectedItem();
        sex=(String)gender.getSelectedItem();

        if((firstname.equals("") )|| (lastname.equals(""))|| (addr.equals(""))||(id.equals(""))||(phone.equals("")))
        {
            JOptionPane.showMessageDialog(null,"please fill the empty fields");
        }
        else
        {
            try {
                result=service.registerUser(
                    id,
                    firstname,
                    lastname,
                    addr,
                    special,
                    sex,
                    account,
                    bsdate,
                    phone);
            } catch (RemoteException ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }

            if(result==""){

                JOptionPane.showMessageDialog(null,"unsucessful operation");

            }
            else{
                JOptionPane.showMessageDialog(null,result);
                try {
                    service.logresgister(ipaddress,username, "Register User",id );
                } catch (RemoteException ex) {
                    Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
                }
                fname.setText("");
                lname.setText("");
                address.setText("");
                personId.setText("");
                phonenumber.setText("");
            }
        }

    }//GEN-LAST:event_RegisterActionPerformed

    private void clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear1ActionPerformed
        // TO clear all the text field:
        fname.setText("");
        lname.setText("");
        address.setText("");
        personId.setText("");
        phonenumber.setText("");
    }//GEN-LAST:event_clear1ActionPerformed

    private void phonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumberActionPerformed

    private void phonenumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenumberKeyPressed
        // TODO add your handling code here:

        char c=evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c))
        {
            phonenumber.setEditable(true);
        }
        else
        {
            phonenumber.setEditable(false);
        }
    }//GEN-LAST:event_phonenumberKeyPressed

    private void reportsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsearchActionPerformed
        DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
        int i=0;
        String fdata;
        tbmodel.setRowCount(0);
        ArrayList flist=new ArrayList();
        try {
                    flist=service.load();
                } catch (RemoteException ex) {
                    Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
                }
        while(i<flist.size())
        {
            fdata=(String) flist.get(i);
            String tbdata[]={fdata};

            tbmodel.addRow(tbdata);
            i++;

        }

        
    }//GEN-LAST:event_reportsearchActionPerformed

    
    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
        String id="";        
        try {
                    service.logresgister(ipaddress,username, "LogOut",id );
                } catch (RemoteException ex) {
                    Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.dispose();
                Login login=new Login();
                login.setVisible(true);

    }//GEN-LAST:event_logout1ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

         selectedIndex=jTabbedPane1.getSelectedIndex();
        if (selectedIndex==0){
           registeruserticker.setVisible(true);
         editprofilerticker.setVisible(false);
         logreportticker.setVisible(false);
        }
        else if(selectedIndex==1)
        {
         registeruserticker.setVisible(false);
         editprofilerticker.setVisible(true);
         logreportticker.setVisible(false);
        }
        else
        {
           registeruserticker.setVisible(false);
         editprofilerticker.setVisible(false);
         logreportticker.setVisible(true);
         
        }



        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Register;
    private javax.swing.JComboBox<String> accountType;
    private javax.swing.JTextField address;
    private javax.swing.JPanel attachfile;
    private javax.swing.JPanel background;
    private com.toedter.calendar.JDateChooser birthdate;
    private javax.swing.JPanel caseReport;
    private javax.swing.JButton changestatususer;
    private javax.swing.JButton clear1;
    private javax.swing.JTextField editacctype;
    private javax.swing.JTextField editaddress;
    private javax.swing.JTextField editfname;
    private javax.swing.JComboBox<String> editgender;
    private javax.swing.JTextField editlname;
    private javax.swing.JTextField editpersonid;
    private javax.swing.JTextField editphone;
    private javax.swing.JLabel editprofilerticker;
    private javax.swing.JButton edituserclear;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lname;
    private javax.swing.JPanel logo;
    private javax.swing.JButton logout1;
    private javax.swing.JLabel logreportticker;
    private javax.swing.JPanel pagedetail;
    private javax.swing.JTextField personId;
    private javax.swing.JTextField phonenumber;
    private javax.swing.JPanel registerUser;
    private javax.swing.JLabel registeruserticker;
    private javax.swing.JButton reportsearch;
    private javax.swing.JButton searchuser;
    private javax.swing.JComboBox<String> specialization;
    private javax.swing.JButton updateuser;
    private javax.swing.JTextField useridsearch;
    // End of variables declaration//GEN-END:variables
}
