/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import AddressFinder.ipfinder;
import Admin.Admin;
import DataEncoder.EncoderHomePage;
import Encryption.encrypt;
import ExcutiveJ.ExecutiveHome;
import ServiceInterface.service;
import java.net.InetAddress;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author AbeXo
 */
public class Login extends javax.swing.JFrame {
    Registry reg;
    service service;
    ipfinder find;
    private static String pswd;
    private static int counter=0;
    
    
    
        public Login() {
        initComponents();
         try{
       reg=LocateRegistry.getRegistry("127.0.0.1", 1099);
       service=(service)reg.lookup("digitalcasemanagment");
       }catch(Exception ex){ex.printStackTrace();}
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        passwordlock = new javax.swing.JToggleButton();
        login = new javax.swing.JButton();
        forgot = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        passwordlock.setBackground(new java.awt.Color(51, 51, 51));
        passwordlock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/show-password (1).png"))); // NOI18N
        passwordlock.setBorder(null);
        passwordlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordlockActionPerformed(evt);
            }
        });
        jPanel2.add(passwordlock);
        passwordlock.setBounds(350, 260, 50, 30);

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/button.JPG"))); // NOI18N
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel2.add(login);
        login.setBounds(60, 380, 280, 40);

        forgot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/button2.JPG"))); // NOI18N
        forgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgotMouseEntered(evt);
            }
        });
        jPanel2.add(forgot);
        forgot.setBounds(100, 320, 160, 30);

        username.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username);
        username.setBounds(60, 150, 280, 30);

        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        jPanel2.add(password);
        password.setBounds(60, 260, 280, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(129, 145, 96));
        jLabel1.setText("User Name");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(160, 120, 110, 17);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/final2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(-40, 0, 960, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordlockActionPerformed
        // TODO add your handling code here:

        if(passwordlock.isSelected())
        {
            password.setEchoChar((char)0);
        }
        else
        {
            password.setEchoChar('*');

        }

    }//GEN-LAST:event_passwordlockActionPerformed
/*
    this method is for login check the user name and password of enterd account information
    and check it is valid then if it valid check the user is login for the first time 
    so forward to change password page to change the default password generated by the system
    */
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
   
String user,pswd;
String account;
String status;
char[] pass=password.getPassword();
String fpassword=new String(pass);
fpassword=encrypt.getHashValue(fpassword);
user=username.getText();

ArrayList ar=new ArrayList();
try{
ar=(ArrayList) service.loginUser(user, fpassword);// calling the remote method in the RMI server
if(ar.size()>0){
    
    status=(String)ar.get(2);
    
    if(ar.get(2).equals("2"))//check if it is user logged into the system for the first time
   {
    account=(String)ar.get(3);
    user=(String)ar.get(0);
    updatepassword upd=new updatepassword();
    upd.setuname(user);
    upd.setaccount(account);
    upd.setVisible(true);
    dispose(); 
   }
    
else if(status.equals("1"))//check if it is user logged into the system is active
   {
       InetAddress ip;
       String ipaddr;
       String username;
 try{
 ip=InetAddress.getLocalHost();
 ipaddr=ip.toString();
 username=(String)ar.get(0);
  find=new ipfinder(ipaddr,username);
 }
 catch(Exception e){
 System.out.println("can't regisster the ip address");
 }
       
    if(ar.get(3).equals("1"))// if the array list object third item is equlas to 1 forwar to Executive Judge home page
   {
        
   ExecutiveHome exehome=new ExecutiveHome();

   exehome.setip(find.getip());
   exehome.setuname(find.getusername());
   service.logresgister(find.getip(),find.getusername(), "login operation","executive judge" );
   exehome.setVisible(true);
   dispose();
   }
   else if(ar.get(3).equals("3"))// if the array list object third item is equlas to 3 forwar to Encoder home page
   {
   EncoderHomePage enchome=new EncoderHomePage();
   enchome.setip(find.getip());
   enchome.setuname(find.getusername());
   service.logresgister(find.getip(),find.getusername(), "login operation","data encoder" );
   enchome.setVisible(true);
   dispose();
   }
   else if(ar.get(3).equals("5"))// if the array list object third item is equlas to 5 forwar to user home page
   {
    userhome usehome=new userhome();
    service.logresgister(find.getip(),find.getusername(), "login operation","user" );
    usehome.setVisible(true);
    dispose();
   }
   else if(ar.get(3).equals("7"))// if the array list object third item is equlas to 7 forwar to Admin home page
   {
  Admin admin=new Admin();
  admin.setip(find.getip());
  admin.setuname(find.getusername());
  service.logresgister(find.getip(),find.getusername(), "login operation","Admin" );
  admin.setVisible(true);
  dispose();
   }
    
   else{
   JOptionPane.showMessageDialog(null,"Account Still Processing Try Again");//display inforamtion
   }
}
   else{
      JOptionPane.showMessageDialog(null,"Contact Admin Account has been Disabled");//display that the account is disabled
   }
    }

else{
    JOptionPane.showMessageDialog(null,"user doesn't exsist");
    System.out.println("error");
}
}catch(Exception e) {
    JOptionPane.showMessageDialog(null,"username and password doesn't exsist");

counter++;
if(counter>3){
dispose();
}       
    //System.out.println("\nException caught");
        }
        
    }//GEN-LAST:event_loginActionPerformed
   
    private void forgotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseEntered
        forgot.setSize(40, 40);        // TODO add your handling code here:
    }//GEN-LAST:event_forgotMouseEntered

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed



        // TODO add your handling code here:
    }//GEN-LAST:event_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton forgot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JToggleButton passwordlock;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
