/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExcutiveJ;

import Login.Login;
import ServiceInterface.service;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author AbeXo
 */
public class ExecutiveHome extends javax.swing.JFrame {
Registry reg;
    service service;
    private String ipaddress;
    private String username;
    private static int selectedIndex;
    /**
     * Creates new form ExecutiveHome
     */
    public ExecutiveHome() {
        initComponents();
        drop.setVisible(false);
        updatecaseview.setVisible(false);
        try{
        
      reg=LocateRegistry.getRegistry("127.0.0.1", 1099);
       service=(service)reg.lookup("digitalcasemanagment");
        }catch(Exception e){
            System.out.println(e.getMessage());}
        
        checkcaseticker.setVisible(true);
        dropcaseticker.setVisible(false);
        casereportticker.setVisible(false);
    
    
    
    }
    
    public void loaddata() throws RemoteException
    {
        ArrayList arlist=new ArrayList();
        arlist=service.load();
    
    for (int i=0;i<arlist.size();i++)
    {
    //if()
        
    }
        
        
    }
    
        public void setuname(String uname)
        {
            this.username=uname;
        }
        public void setip(String ipaddr)
        {
            this.ipaddress=ipaddr;
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        attachwitness = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        viewSingleCaseNumber1 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel85 = new javax.swing.JLabel();
        casetitleedit1 = new javax.swing.JTextField();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        summarycaseedit1 = new javax.swing.JTextArea();
        searchcase1 = new javax.swing.JButton();
        updatecaseview = new javax.swing.JButton();
        clearviewcase1 = new javax.swing.JButton();
        judgecase1 = new javax.swing.JTextField();
        Checkcase = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        viewSingleCaseNumber = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel81 = new javax.swing.JLabel();
        casetitleedit = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        summarycaseedit = new javax.swing.JTextArea();
        searchcase = new javax.swing.JButton();
        clearviewcase = new javax.swing.JButton();
        judgecase = new javax.swing.JTextField();
        drop = new javax.swing.JButton();
        caseReport = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        subcategory = new javax.swing.JComboBox<>();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        jLabel72 = new javax.swing.JLabel();
        reportremark = new javax.swing.JComboBox<>();
        reportsearch = new javax.swing.JButton();
        jLabel79 = new javax.swing.JLabel();
        pagedetail = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        casereportticker = new javax.swing.JLabel();
        logout1 = new javax.swing.JButton();
        checkcaseticker = new javax.swing.JLabel();
        dropcaseticker = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(25, 51, 59));

        jTabbedPane1.setBackground(new java.awt.Color(25, 51, 59));
        jTabbedPane1.setName("MENU"); // NOI18N
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(300, 200));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel84.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel84.setText("Case Number");

        viewSingleCaseNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSingleCaseNumber1ActionPerformed(evt);
            }
        });
        viewSingleCaseNumber1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                viewSingleCaseNumber1KeyPressed(evt);
            }
        });

        jSeparator10.setBackground(new java.awt.Color(33, 139, 209));
        jSeparator10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel85.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel85.setText("Title");

        casetitleedit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casetitleedit1ActionPerformed(evt);
            }
        });
        casetitleedit1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                casetitleedit1KeyPressed(evt);
            }
        });

        jLabel86.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel86.setText("Assigned Judge");

        jLabel87.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel87.setText("Summary");

        summarycaseedit1.setColumns(20);
        summarycaseedit1.setRows(5);
        jScrollPane5.setViewportView(summarycaseedit1);

        searchcase1.setBackground(new java.awt.Color(0, 0, 0));
        searchcase1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchcase1.setForeground(new java.awt.Color(255, 255, 255));
        searchcase1.setText("Search");
        searchcase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchcase1ActionPerformed(evt);
            }
        });

        updatecaseview.setBackground(new java.awt.Color(0, 0, 0));
        updatecaseview.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        updatecaseview.setForeground(new java.awt.Color(255, 255, 255));
        updatecaseview.setText("Update Case");
        updatecaseview.setVisible(false);
        updatecaseview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatecaseviewActionPerformed(evt);
            }
        });

        clearviewcase1.setBackground(new java.awt.Color(0, 0, 0));
        clearviewcase1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clearviewcase1.setForeground(new java.awt.Color(255, 255, 255));
        clearviewcase1.setText("Cancel");
        clearviewcase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearviewcase1ActionPerformed(evt);
            }
        });

        judgecase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judgecase1ActionPerformed(evt);
            }
        });
        judgecase1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                judgecase1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout attachwitnessLayout = new javax.swing.GroupLayout(attachwitness);
        attachwitness.setLayout(attachwitnessLayout);
        attachwitnessLayout.setHorizontalGroup(
            attachwitnessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attachwitnessLayout.createSequentialGroup()
                .addGroup(attachwitnessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attachwitnessLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(attachwitnessLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(attachwitnessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(attachwitnessLayout.createSequentialGroup()
                                .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(casetitleedit1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(attachwitnessLayout.createSequentialGroup()
                                .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewSingleCaseNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(searchcase1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(attachwitnessLayout.createSequentialGroup()
                                .addComponent(jLabel86, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(judgecase1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(attachwitnessLayout.createSequentialGroup()
                                .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(attachwitnessLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(updatecaseview)
                        .addGap(33, 33, 33)
                        .addComponent(clearviewcase1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        attachwitnessLayout.setVerticalGroup(
            attachwitnessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attachwitnessLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(attachwitnessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(attachwitnessLayout.createSequentialGroup()
                        .addGroup(attachwitnessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(attachwitnessLayout.createSequentialGroup()
                                .addGroup(attachwitnessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewSingleCaseNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchcase1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(attachwitnessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(casetitleedit1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel86))
                    .addComponent(judgecase1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(attachwitnessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attachwitnessLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel87))
                    .addGroup(attachwitnessLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(attachwitnessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatecaseview, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearviewcase1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edit Case", attachwitness);

        jLabel80.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel80.setText("Case Number");

        viewSingleCaseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSingleCaseNumberActionPerformed(evt);
            }
        });
        viewSingleCaseNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                viewSingleCaseNumberKeyPressed(evt);
            }
        });

        jSeparator9.setBackground(new java.awt.Color(33, 139, 209));
        jSeparator9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel81.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel81.setText("Title");

        casetitleedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casetitleeditActionPerformed(evt);
            }
        });
        casetitleedit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                casetitleeditKeyPressed(evt);
            }
        });

        jLabel82.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel82.setText("Assigned Judge");

        jLabel83.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel83.setText("Summary");

        summarycaseedit.setColumns(20);
        summarycaseedit.setRows(5);
        jScrollPane4.setViewportView(summarycaseedit);

        searchcase.setBackground(new java.awt.Color(0, 0, 0));
        searchcase.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchcase.setForeground(new java.awt.Color(255, 255, 255));
        searchcase.setText("Search");
        searchcase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchcaseActionPerformed(evt);
            }
        });

        clearviewcase.setBackground(new java.awt.Color(0, 0, 0));
        clearviewcase.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clearviewcase.setForeground(new java.awt.Color(255, 255, 255));
        clearviewcase.setText("Cancel");
        clearviewcase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearviewcaseActionPerformed(evt);
            }
        });

        judgecase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judgecaseActionPerformed(evt);
            }
        });
        judgecase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                judgecaseKeyPressed(evt);
            }
        });

        drop.setBackground(new java.awt.Color(0, 0, 0));
        drop.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        drop.setForeground(new java.awt.Color(255, 255, 255));
        drop.setText("Drop");
        drop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CheckcaseLayout = new javax.swing.GroupLayout(Checkcase);
        Checkcase.setLayout(CheckcaseLayout);
        CheckcaseLayout.setHorizontalGroup(
            CheckcaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckcaseLayout.createSequentialGroup()
                .addGroup(CheckcaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CheckcaseLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CheckcaseLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(CheckcaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CheckcaseLayout.createSequentialGroup()
                                .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(casetitleedit, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CheckcaseLayout.createSequentialGroup()
                                .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewSingleCaseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(searchcase, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CheckcaseLayout.createSequentialGroup()
                                .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(judgecase, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CheckcaseLayout.createSequentialGroup()
                                .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CheckcaseLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(drop, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(clearviewcase, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        CheckcaseLayout.setVerticalGroup(
            CheckcaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckcaseLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(CheckcaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CheckcaseLayout.createSequentialGroup()
                        .addGroup(CheckcaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(CheckcaseLayout.createSequentialGroup()
                                .addGroup(CheckcaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewSingleCaseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchcase, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(CheckcaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(casetitleedit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel82))
                    .addComponent(judgecase, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CheckcaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CheckcaseLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel83))
                    .addGroup(CheckcaseLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addGroup(CheckcaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearviewcase, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drop, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Drop Case", Checkcase);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Case Number", "Start Date", "Assigned Judge", "Status", "Category", "Remark"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        subcategory.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        subcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Civil Affairs", "Criminal Trial", "Labor Dispute" }));
        subcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subcategoryActionPerformed(evt);
            }
        });

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel56.setText("Case Subcategory");

        jLabel57.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel57.setText("Case Status");

        status.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Normal", "Special", "Confidential" }));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });

        jLabel72.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel72.setText("Case Remark");

        reportremark.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        reportremark.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "unfinished", "finished" }));
        reportremark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportremarkActionPerformed(evt);
            }
        });

        reportsearch.setBackground(new java.awt.Color(0, 0, 0));
        reportsearch.setForeground(new java.awt.Color(255, 255, 255));
        reportsearch.setText("Search");
        reportsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsearchActionPerformed(evt);
            }
        });

        jLabel79.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel79.setText("Select your categories ");

        javax.swing.GroupLayout caseReportLayout = new javax.swing.GroupLayout(caseReport);
        caseReport.setLayout(caseReportLayout);
        caseReportLayout.setHorizontalGroup(
            caseReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caseReportLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(caseReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(caseReportLayout.createSequentialGroup()
                        .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(caseReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(caseReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(caseReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(caseReportLayout.createSequentialGroup()
                                .addComponent(reportremark, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(reportsearch)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        caseReportLayout.setVerticalGroup(
            caseReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caseReportLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(caseReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(jLabel57)
                    .addComponent(jLabel72))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(caseReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportremark, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel79)
                    .addComponent(reportsearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Case Report", caseReport);

        pagedetail.setBackground(new java.awt.Color(60, 83, 89));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Federal First Degree Court Of Ethiopia");

        javax.swing.GroupLayout pagedetailLayout = new javax.swing.GroupLayout(pagedetail);
        pagedetail.setLayout(pagedetailLayout);
        pagedetailLayout.setHorizontalGroup(
            pagedetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagedetailLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pagedetailLayout.setVerticalGroup(
            pagedetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagedetailLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        logo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataEncoder/logosfinal.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(49, 152, 222));
        jLabel2.setText("Digital Case Managment");

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 756, Short.MAX_VALUE))
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Case Report");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataEncoder/003-case-study.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataEncoder/001-closed-suitcase.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Drop Case");

        jLabel22.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataEncoder/001-note.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Check Case ");

        casereportticker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataEncoder/check.png"))); // NOI18N

        logout1.setBackground(new java.awt.Color(25, 51, 59));
        logout1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        logout1.setForeground(new java.awt.Color(255, 255, 255));
        logout1.setText("Log Out");
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });

        checkcaseticker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataEncoder/check.png"))); // NOI18N

        dropcaseticker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataEncoder/check.png"))); // NOI18N

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel25)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dropcaseticker, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(casereportticker, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkcaseticker, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addComponent(pagedetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagedetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkcaseticker, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dropcaseticker, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casereportticker, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)))
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout1)
                .addGap(129, 129, 129))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reportsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsearchActionPerformed
        DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
        tbmodel.setRowCount(0);

        ArrayList clist=new ArrayList();
        String subcat,casestat,caserem;
        String query;
        subcat=(String)subcategory.getSelectedItem();
        casestat=(String)status.getSelectedItem();
        caserem=(String) reportremark.getSelectedItem();
        String logdata=subcat+","+casestat+","+caserem;
        int i=0;
        String casenum,startdate,assindedj,status,cat,remark;

    try {
        clist=(ArrayList)service.viewReport(subcat,caserem ,casestat );
        try {
                    service.logresgister(ipaddress,username, "View Case Report",logdata );
                } catch (RemoteException ex) {
                    Logger.getLogger(ExecutiveHome.class.getName()).log(Level.SEVERE, null, ex);
                }
    } catch (RemoteException ex) {
        Logger.getLogger(ExecutiveHome.class.getName()).log(Level.SEVERE, null, ex);
    }

        while(i<clist.size())
        {
            casenum=(String)clist.get(i);
            startdate=(String)clist.get(i+1);
            assindedj=(String)clist.get(i+2);
            status=(String)clist.get(i+3);
            cat=(String)clist.get(i+4);
            remark=(String)clist.get(i+5);
            String tbdata[]={casenum,startdate,assindedj,status,cat,remark};

            tbmodel.addRow(tbdata);
            i=i+6;

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_reportsearchActionPerformed

    private void reportremarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportremarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportremarkActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void subcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subcategoryActionPerformed

    private void judgecaseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_judgecaseKeyPressed
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isISOControl(c))
        {
            judgecase.setEditable(true);
        }
        else
        {
            judgecase.setEditable(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_judgecaseKeyPressed

    private void judgecaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judgecaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judgecaseActionPerformed

    private void clearviewcaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearviewcaseActionPerformed

        casetitleedit.setText("");
        summarycaseedit.setText("");
        judgecase.setText("");
        viewSingleCaseNumber.setEditable(true);
    }//GEN-LAST:event_clearviewcaseActionPerformed

    private void searchcaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchcaseActionPerformed
        String casenumber;
        ArrayList singlecaselist=new ArrayList();

        casenumber=viewSingleCaseNumber.getText();
        if(casenumber.equals("")){JOptionPane.showMessageDialog(null,"fill the case number");}
        else{
            try {
                singlecaselist=(ArrayList)service.viewCase(casenumber);
                try {
                    service.logresgister(ipaddress,username, "check case to drop", casenumber);
                } catch (RemoteException ex) {
                    Logger.getLogger(ExecutiveHome.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (RemoteException ex) {
                Logger.getLogger(ExecutiveHome.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(singlecaselist.size()>1)
            {
                casetitleedit.setText((String) singlecaselist.get(0));//set the case title input field by arraylsit first item
                summarycaseedit.setText((String) singlecaselist.get(1));//set the case description input field by arraylsit secomd item
                judgecase.setText((String) singlecaselist.get(2));//set the case Assigned judge input field by arraylsit third item
                drop.setVisible(true);//maker the drop case button visibles
                
                casetitleedit.setEditable(false);//make the title input field non editable
                summarycaseedit.setEditable(false);//make the summary case input field non editable
                judgecase.setEditable(false);//make the Assigned judge input field non editable
                viewSingleCaseNumber.setEditable(false);//make the cazse number input field non editable
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"case not found");
            }
        }
    }//GEN-LAST:event_searchcaseActionPerformed

    private void casetitleeditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_casetitleeditKeyPressed
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isISOControl(c))
        {
            casetitleedit.setEditable(true);
        }
        else
        {
            casetitleedit.setEditable(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_casetitleeditKeyPressed

    private void casetitleeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casetitleeditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casetitleeditActionPerformed

    private void viewSingleCaseNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_viewSingleCaseNumberKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewSingleCaseNumberKeyPressed

    private void viewSingleCaseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSingleCaseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewSingleCaseNumberActionPerformed
/*
    this  method will make the case dropped from active state to inactive 
    in case table 
    */
    private void dropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropActionPerformed
        String result;
        String casenumber;
        
        casenumber=viewSingleCaseNumber.getText();
        try {
                result=service.closecasedecision(casenumber);
        if(result.equals("successful operation"))
        { 
            try {
                    service.logresgister(ipaddress,username, "Drop case", casenumber);
                } catch (RemoteException ex) {
                    Logger.getLogger(ExecutiveHome.class.getName()).log(Level.SEVERE, null, ex);
                }
            JOptionPane.showMessageDialog(null,"sucessful operation");
             viewSingleCaseNumber.setText("");//set the first name field empty after the operation
             casetitleedit.setText("");//set the last name field empty after the operation
             judgecase.setText("");//set the address field empty after the operation
             summarycaseedit.setText("");//set the phone number field empty after the operation
             drop.setVisible(false);
             viewSingleCaseNumber.setEditable(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"unsucessful operation");
        }
        } catch (RemoteException ex) {
                Logger.getLogger(ExecutiveHome.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        
        



    }//GEN-LAST:event_dropActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
            
         selectedIndex=jTabbedPane1.getSelectedIndex();
        if (selectedIndex==0)
        {
        checkcaseticker.setVisible(true);
        dropcaseticker.setVisible(false);
        casereportticker.setVisible(false);
        }
        else if(selectedIndex==1)
        {
        checkcaseticker.setVisible(false);
        dropcaseticker.setVisible(true);
        casereportticker.setVisible(false);
        }
        else
        {
        checkcaseticker.setVisible(false);
        dropcaseticker.setVisible(false);
        casereportticker.setVisible(true);
        }
   
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void viewSingleCaseNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSingleCaseNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewSingleCaseNumber1ActionPerformed

    private void viewSingleCaseNumber1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_viewSingleCaseNumber1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewSingleCaseNumber1KeyPressed

    private void casetitleedit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casetitleedit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casetitleedit1ActionPerformed

    private void casetitleedit1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_casetitleedit1KeyPressed
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isISOControl(c))
        {
            casetitleedit.setEditable(true);
        }
        else
        {
            casetitleedit.setEditable(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_casetitleedit1KeyPressed

    private void searchcase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchcase1ActionPerformed
        String casenumber;
        ArrayList singlecaselist=new ArrayList();

        casenumber=viewSingleCaseNumber1.getText();
        if(casenumber.equals("")){JOptionPane.showMessageDialog(null,"fill the case number");}
        else{
            try {
                singlecaselist=(ArrayList)service.viewCase(casenumber);
                try {
                    service.logresgister(ipaddress,username, "check case to edit", casenumber);
                } catch (RemoteException ex) {
                    Logger.getLogger(ExecutiveHome.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (RemoteException ex) {
                Logger.getLogger(ExecutiveHome.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(singlecaselist.size()>1)
            {
                // JOptionPane.showMessageDialog(null,"case found");
                casetitleedit1.setText((String) singlecaselist.get(0));
                summarycaseedit1.setText((String) singlecaselist.get(1));
                judgecase1.setText((String) singlecaselist.get(2));
                updatecaseview.setVisible(true);

            }
            else
            {
                JOptionPane.showMessageDialog(null,"case not sfound");
            }
        }
    }//GEN-LAST:event_searchcase1ActionPerformed

    private void updatecaseviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatecaseviewActionPerformed
        String casenumber,ctitile,cdesc,cjudge;
        String result = null;
        casenumber=viewSingleCaseNumber1.getText();
        ctitile=casetitleedit1.getText();
        cdesc=summarycaseedit1.getText();
        cjudge=judgecase1.getText();

        if((ctitile.equals(""))||(cdesc.equals(""))|| cjudge.equals("")){JOptionPane.showMessageDialog(null,"fill out empty fields");}
        else{
            try {
                result=service.updatecase(casenumber,ctitile,cdesc,cjudge);
            } catch (RemoteException ex) {
                Logger.getLogger(ExecutiveHome.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(result.equals("successful operation"))
            {
                try {
                    service.logresgister(ipaddress,username, "Update case information", casenumber);
                } catch (RemoteException ex) {
                    Logger.getLogger(ExecutiveHome.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null,"successful operation");
                casetitleedit1.setText("");
                summarycaseedit1.setText("");
                judgecase1.setText("");
                updatecaseview.setVisible(false);
            }
            else{JOptionPane.showMessageDialog(null,"unsuccessful operation");}

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_updatecaseviewActionPerformed

    private void clearviewcase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearviewcase1ActionPerformed

        casetitleedit.setText("");
        summarycaseedit.setText("");
        judgecase.setText("");
        updatecaseview.setVisible(false);
        viewSingleCaseNumber1.setText("");
    }//GEN-LAST:event_clearviewcase1ActionPerformed

    private void judgecase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judgecase1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judgecase1ActionPerformed

    private void judgecase1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_judgecase1KeyPressed
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isISOControl(c))
        {
            judgecase.setEditable(true);
        }
        else
        {
            judgecase.setEditable(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_judgecase1KeyPressed

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed

      String id="";        
        try {
                    service.logresgister(ipaddress,username, "LogOut",id );
                } catch (RemoteException ex) {
                    Logger.getLogger(ExecutiveHome.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.dispose();
                Login login=new Login();
                login.setVisible(true);

    }//GEN-LAST:event_logout1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExecutiveHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExecutiveHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExecutiveHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExecutiveHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExecutiveHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Checkcase;
    private javax.swing.JPanel attachwitness;
    private javax.swing.JPanel background;
    private javax.swing.JPanel caseReport;
    private javax.swing.JLabel casereportticker;
    private javax.swing.JTextField casetitleedit;
    private javax.swing.JTextField casetitleedit1;
    private javax.swing.JLabel checkcaseticker;
    private javax.swing.JButton clearviewcase;
    private javax.swing.JButton clearviewcase1;
    private javax.swing.JButton drop;
    private javax.swing.JLabel dropcaseticker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField judgecase;
    private javax.swing.JTextField judgecase1;
    private javax.swing.JPanel logo;
    private javax.swing.JButton logout1;
    private javax.swing.JPanel pagedetail;
    private javax.swing.JComboBox<String> reportremark;
    private javax.swing.JButton reportsearch;
    private javax.swing.JButton searchcase;
    private javax.swing.JButton searchcase1;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JComboBox<String> subcategory;
    private javax.swing.JTextArea summarycaseedit;
    private javax.swing.JTextArea summarycaseedit1;
    private javax.swing.JButton updatecaseview;
    private javax.swing.JTextField viewSingleCaseNumber;
    private javax.swing.JTextField viewSingleCaseNumber1;
    // End of variables declaration//GEN-END:variables
}
